---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: stargate-postgres-data
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: stargate-postgres
  labels:
    app: stargate-postgres
spec:
  replicas: 1
  selector:
    matchLabels:
      app: stargate-postgres
  template:
    metadata:
      labels:
        app: stargate-postgres
    spec:
      containers:
      - name: postgres
        image: registry.redhat.io/rhel9/postgresql-16:latest
        env:
        - name: POSTGRESQL_USER
          valueFrom:
            secretKeyRef:
              name: summit-demo-factory-db
              key: postgres-user
        - name: POSTGRESQL_PASSWORD
          valueFrom:
            secretKeyRef:
              name: summit-demo-factory-db
              key: postgres-password
        - name: POSTGRESQL_DATABASE
          value: stargate
        ports:
        - containerPort: 5432
        volumeMounts:
        - name: data
          mountPath: /var/lib/pgsql/data
        resources:
          requests:
            cpu: 250m
            memory: 256Mi
          limits:
            cpu: '1'
            memory: 512Mi
        securityContext:
          allowPrivilegeEscalation: false
          capabilities:
            drop:
            - ALL
      volumes:
      - name: data
        persistentVolumeClaim:
          claimName: stargate-postgres-data
      securityContext:
        runAsNonRoot: true
        seccompProfile:
          type: RuntimeDefault

---
apiVersion: v1
kind: Service
metadata:
  name: stargate-postgres
  labels:
    app: stargate-postgres
spec:
  selector:
    app: stargate-postgres
  ports:
  - port: 5432
