"""initial schema

Revision ID: 87394f2021f5
Revises: 
Create Date: 2026-05-11 12:47:54.801060

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '87394f2021f5'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_cv_lab'), table_name='constraint_violations')
    op.drop_index(op.f('ix_cv_type'), table_name='constraint_violations')
    op.create_index(op.f('ix_constraint_violations_lab_code'), 'constraint_violations', ['lab_code'], unique=False)
    op.create_index(op.f('ix_constraint_violations_violation_type'), 'constraint_violations', ['violation_type'], unique=False)
    op.drop_index(op.f('idx_llm_metrics_called_at'), table_name='llm_metrics')
    op.drop_index(op.f('idx_llm_metrics_endpoint'), table_name='llm_metrics')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('idx_llm_metrics_endpoint'), 'llm_metrics', ['endpoint'], unique=False)
    op.create_index(op.f('idx_llm_metrics_called_at'), 'llm_metrics', ['called_at'], unique=False)
    op.drop_index(op.f('ix_constraint_violations_violation_type'), table_name='constraint_violations')
    op.drop_index(op.f('ix_constraint_violations_lab_code'), table_name='constraint_violations')
    op.create_index(op.f('ix_cv_type'), 'constraint_violations', ['violation_type'], unique=False)
    op.create_index(op.f('ix_cv_lab'), 'constraint_violations', ['lab_code'], unique=False)
    # ### end Alembic commands ###
