"""baseline_full_schema

Revision ID: faff0a4b8665
Revises: c3d4e5f6g7h8
Create Date: 2026-08-21 09:05:43.059090

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'faff0a4b8665'
down_revision: Union[str, Sequence[str], None] = 'c3d4e5f6g7h8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('aap_job_metrics',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('captured_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('total_jobs', sa.Integer(), nullable=False),
    sa.Column('successful', sa.Integer(), nullable=False),
    sa.Column('failed', sa.Integer(), nullable=False),
    sa.Column('running', sa.Integer(), nullable=False),
    sa.Column('success_rate', sa.Float(), nullable=True),
    sa.Column('provision_sli', sa.Float(), nullable=True),
    sa.Column('sli_met', sa.Boolean(), nullable=True),
    sa.Column('top_error', sa.String(length=500), nullable=True),
    sa.Column('by_cluster', postgresql.JSON(astext_type=Text()), nullable=True),
    sa.Column('by_lab', postgresql.JSON(astext_type=Text()), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_aap_job_metrics_captured_at'), 'aap_job_metrics', ['captured_at'], unique=False)
    op.create_table('audit_log',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('action_type', sa.String(length=100), nullable=False),
    sa.Column('target', sa.String(length=255), nullable=False),
    sa.Column('parameters', postgresql.JSON(astext_type=Text()), nullable=True),
    sa.Column('proposed_by', sa.String(length=255), nullable=True),
    sa.Column('approved_by', sa.String(length=255), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('executed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('result', sa.Text(), nullable=True),
    sa.Column('rollback_available', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_audit_log_action_type'), 'audit_log', ['action_type'], unique=False)
    op.create_table('constraint_violations',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('lab_code', sa.String(length=255), nullable=False),
    sa.Column('violation_type', sa.String(length=255), nullable=False),
    sa.Column('expected', sa.Text(), nullable=True),
    sa.Column('actual', sa.Text(), nullable=True),
    sa.Column('severity', sa.String(length=50), nullable=False),
    sa.Column('detail', sa.Text(), nullable=True),
    sa.Column('correlated_stage', sa.String(length=255), nullable=True),
    sa.Column('correlated_failure_class', sa.String(length=255), nullable=True),
    sa.Column('detected_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_constraint_violations_lab_code'), 'constraint_violations', ['lab_code'], unique=False)
    op.create_index(op.f('ix_constraint_violations_violation_type'), 'constraint_violations', ['violation_type'], unique=False)
    op.create_table('evaluations',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('run_id', sa.String(length=255), nullable=False),
    sa.Column('stage_id', sa.String(length=255), nullable=False),
    sa.Column('outcome', sa.String(length=50), nullable=False),
    sa.Column('failure_class', sa.String(length=255), nullable=True),
    sa.Column('sub_class', sa.String(length=255), nullable=True),
    sa.Column('message', sa.Text(), nullable=True),
    sa.Column('criteria_results', postgresql.JSON(astext_type=Text()), nullable=True),
    sa.Column('evaluated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('lab_code', sa.String(length=255), nullable=True),
    sa.Column('cluster_name', sa.String(length=255), nullable=True),
    sa.Column('human_confirmed', sa.Boolean(), nullable=True),
    sa.Column('human_corrected_class', sa.String(length=255), nullable=True),
    sa.Column('human_notes', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_eval_cluster_outcome', 'evaluations', ['cluster_name', 'outcome'], unique=False)
    op.create_index('idx_eval_lab_cluster', 'evaluations', ['lab_code', 'cluster_name'], unique=False)
    op.create_index('idx_eval_lab_stage', 'evaluations', ['lab_code', 'stage_id'], unique=False)
    op.create_index(op.f('ix_evaluations_cluster_name'), 'evaluations', ['cluster_name'], unique=False)
    op.create_index(op.f('ix_evaluations_failure_class'), 'evaluations', ['failure_class'], unique=False)
    op.create_index(op.f('ix_evaluations_lab_code'), 'evaluations', ['lab_code'], unique=False)
    op.create_index(op.f('ix_evaluations_run_id'), 'evaluations', ['run_id'], unique=False)
    op.create_index(op.f('ix_evaluations_stage_id'), 'evaluations', ['stage_id'], unique=False)
    op.create_index(op.f('ix_evaluations_sub_class'), 'evaluations', ['sub_class'], unique=False)
    op.create_table('event_log',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('event_id', sa.String(length=255), nullable=False),
    sa.Column('event_type', sa.String(length=100), nullable=False),
    sa.Column('timestamp', sa.DateTime(timezone=True), nullable=False),
    sa.Column('run_id', sa.String(length=255), nullable=True),
    sa.Column('stage_id', sa.String(length=255), nullable=True),
    sa.Column('lab_code', sa.String(length=255), nullable=True),
    sa.Column('cluster_name', sa.String(length=255), nullable=True),
    sa.Column('outcome', sa.String(length=50), nullable=True),
    sa.Column('failure_class', sa.String(length=255), nullable=True),
    sa.Column('message', sa.Text(), nullable=True),
    sa.Column('priority', sa.Float(), nullable=False),
    sa.Column('systemic', sa.Boolean(), nullable=False),
    sa.Column('filtered', sa.Boolean(), nullable=False),
    sa.Column('blast_radius', postgresql.JSON(astext_type=Text()), nullable=True),
    sa.Column('metadata_json', postgresql.JSON(astext_type=Text()), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_event_log_cluster_name'), 'event_log', ['cluster_name'], unique=False)
    op.create_index(op.f('ix_event_log_event_id'), 'event_log', ['event_id'], unique=True)
    op.create_index(op.f('ix_event_log_event_type'), 'event_log', ['event_type'], unique=False)
    op.create_index(op.f('ix_event_log_failure_class'), 'event_log', ['failure_class'], unique=False)
    op.create_index(op.f('ix_event_log_lab_code'), 'event_log', ['lab_code'], unique=False)
    op.create_index(op.f('ix_event_log_stage_id'), 'event_log', ['stage_id'], unique=False)
    op.create_table('evidence',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('evidence_id', sa.String(length=255), nullable=False),
    sa.Column('run_id', sa.String(length=255), nullable=False),
    sa.Column('stage_id', sa.String(length=255), nullable=False),
    sa.Column('type', sa.String(length=255), nullable=False),
    sa.Column('source', sa.String(length=255), nullable=False),
    sa.Column('resource', postgresql.JSON(astext_type=Text()), nullable=True),
    sa.Column('observed', postgresql.JSON(astext_type=Text()), nullable=False),
    sa.Column('result', sa.String(length=50), nullable=False),
    sa.Column('timestamp', sa.DateTime(timezone=True), nullable=False),
    sa.Column('raw_ref', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_evidence_evidence_id'), 'evidence', ['evidence_id'], unique=True)
    op.create_index(op.f('ix_evidence_run_id'), 'evidence', ['run_id'], unique=False)
    op.create_index(op.f('ix_evidence_stage_id'), 'evidence', ['stage_id'], unique=False)
    op.create_table('investigations',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('job_id', sa.String(length=255), nullable=False),
    sa.Column('lab_code', sa.String(length=255), nullable=False),
    sa.Column('cluster', sa.String(length=100), nullable=True),
    sa.Column('namespace', sa.String(length=255), nullable=True),
    sa.Column('failure_class', sa.String(length=255), nullable=True),
    sa.Column('trigger_type', sa.String(length=50), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('triggering_eval_id', sa.Integer(), nullable=True),
    sa.Column('analysis', sa.Text(), nullable=True),
    sa.Column('tool_calls', postgresql.JSON(astext_type=Text()), nullable=True),
    sa.Column('iterations', sa.Integer(), nullable=True),
    sa.Column('model_used', sa.String(length=255), nullable=True),
    sa.Column('cost_estimate', sa.Float(), nullable=True),
    sa.Column('root_cause', sa.String(length=500), nullable=True),
    sa.Column('remediation_suggestion', sa.Text(), nullable=True),
    sa.Column('codebase_link', sa.String(length=500), nullable=True),
    sa.Column('trust_dimensions', postgresql.JSON(astext_type=Text()), nullable=True),
    sa.Column('resolved_by_id', sa.Integer(), nullable=True),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('fallback', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_inv_lab_fc', 'investigations', ['lab_code', 'failure_class'], unique=False)
    op.create_index('idx_inv_status', 'investigations', ['status'], unique=False)
    op.create_index(op.f('ix_investigations_cluster'), 'investigations', ['cluster'], unique=False)
    op.create_index(op.f('ix_investigations_failure_class'), 'investigations', ['failure_class'], unique=False)
    op.create_index(op.f('ix_investigations_job_id'), 'investigations', ['job_id'], unique=True)
    op.create_index(op.f('ix_investigations_lab_code'), 'investigations', ['lab_code'], unique=False)
    op.create_table('lab_mappings',
    sa.Column('lab_code', sa.String(length=50), nullable=False),
    sa.Column('ci_name', sa.String(length=255), nullable=True),
    sa.Column('ci_base', sa.String(length=100), nullable=True),
    sa.Column('ci_slug', sa.String(length=255), nullable=True),
    sa.Column('namespace_pattern', sa.String(length=100), nullable=True),
    sa.Column('pool_pattern', sa.String(length=100), nullable=True),
    sa.Column('agnosticv_path', sa.String(length=255), nullable=True),
    sa.Column('cloud', sa.String(length=50), nullable=True),
    sa.Column('clusters', postgresql.JSON(astext_type=Text()), nullable=True),
    sa.Column('owner', sa.String(length=255), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('lab_code')
    )
    op.create_index(op.f('ix_lab_mappings_ci_base'), 'lab_mappings', ['ci_base'], unique=False)
    op.create_table('lab_remediation_config',
    sa.Column('lab_code', sa.String(length=50), nullable=False),
    sa.Column('execution_mode', sa.String(length=30), nullable=False),
    sa.Column('max_actions_per_hour', sa.Integer(), nullable=False),
    sa.Column('enabled_by', sa.String(length=255), nullable=True),
    sa.Column('enabled_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('lab_code')
    )
    op.create_table('llm_feedback',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('llm_metric_id', sa.Integer(), nullable=True),
    sa.Column('endpoint', sa.String(length=100), nullable=False),
    sa.Column('helpful', sa.Boolean(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('submitted_by', sa.String(length=255), nullable=True),
    sa.Column('submitted_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_llm_feedback_llm_metric_id'), 'llm_feedback', ['llm_metric_id'], unique=False)
    op.create_table('llm_metrics',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('endpoint', sa.String(length=100), nullable=False),
    sa.Column('model', sa.String(length=255), nullable=False),
    sa.Column('prompt_tokens', sa.Integer(), nullable=True),
    sa.Column('completion_tokens', sa.Integer(), nullable=True),
    sa.Column('total_tokens', sa.Integer(), nullable=True),
    sa.Column('cost_estimate', sa.Float(), nullable=True),
    sa.Column('latency_ms', sa.Integer(), nullable=False),
    sa.Column('success', sa.Boolean(), nullable=False),
    sa.Column('finish_reason', sa.String(length=50), nullable=True),
    sa.Column('error_type', sa.String(length=100), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('prompt_hash', sa.String(length=64), nullable=True),
    sa.Column('response_preview', sa.Text(), nullable=True),
    sa.Column('lab_code', sa.String(length=255), nullable=True),
    sa.Column('cluster_name', sa.String(length=255), nullable=True),
    sa.Column('failure_class', sa.String(length=255), nullable=True),
    sa.Column('confidence', sa.Float(), nullable=True),
    sa.Column('adjusted_confidence', sa.Float(), nullable=True),
    sa.Column('prompt_version', sa.String(length=50), nullable=True),
    sa.Column('called_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_llm_metrics_called_at'), 'llm_metrics', ['called_at'], unique=False)
    op.create_index(op.f('ix_llm_metrics_endpoint'), 'llm_metrics', ['endpoint'], unique=False)
    op.create_index(op.f('ix_llm_metrics_lab_code'), 'llm_metrics', ['lab_code'], unique=False)
    op.create_index(op.f('ix_llm_metrics_prompt_hash'), 'llm_metrics', ['prompt_hash'], unique=False)
    op.create_table('mv_cluster_summary',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('cluster_name', sa.String(length=255), nullable=False),
    sa.Column('total_evaluations', sa.Integer(), nullable=False),
    sa.Column('passed', sa.Integer(), nullable=False),
    sa.Column('failed', sa.Integer(), nullable=False),
    sa.Column('warned', sa.Integer(), nullable=False),
    sa.Column('health_rate', sa.Float(), nullable=False),
    sa.Column('failure_classes', postgresql.JSON(astext_type=Text()), nullable=True),
    sa.Column('labs_seen', sa.Integer(), nullable=False),
    sa.Column('labs_failing', sa.Integer(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_mv_cluster_summary_cluster_name'), 'mv_cluster_summary', ['cluster_name'], unique=True)
    op.create_table('mv_evaluation_trends',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('bucket', sa.DateTime(timezone=True), nullable=False),
    sa.Column('cluster_name', sa.String(length=255), nullable=True),
    sa.Column('outcome', sa.String(length=50), nullable=False),
    sa.Column('failure_class', sa.String(length=255), nullable=True),
    sa.Column('count', sa.Integer(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_mv_evaluation_trends_bucket'), 'mv_evaluation_trends', ['bucket'], unique=False)
    op.create_index(op.f('ix_mv_evaluation_trends_cluster_name'), 'mv_evaluation_trends', ['cluster_name'], unique=False)
    op.create_table('mv_lab_eval_summary',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('lab_code', sa.String(length=255), nullable=False),
    sa.Column('cluster_name', sa.String(length=255), nullable=True),
    sa.Column('total_evals', sa.Integer(), nullable=False),
    sa.Column('passed', sa.Integer(), nullable=False),
    sa.Column('failed', sa.Integer(), nullable=False),
    sa.Column('warned', sa.Integer(), nullable=False),
    sa.Column('top_failure_class', sa.String(length=255), nullable=True),
    sa.Column('health_rate', sa.Float(), nullable=False),
    sa.Column('last_evaluated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_mv_lab_eval_summary_cluster_name'), 'mv_lab_eval_summary', ['cluster_name'], unique=False)
    op.create_index(op.f('ix_mv_lab_eval_summary_lab_code'), 'mv_lab_eval_summary', ['lab_code'], unique=False)
    op.create_table('mv_mttr_by_class',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('failure_class', sa.String(length=255), nullable=False),
    sa.Column('incident_count', sa.Integer(), nullable=False),
    sa.Column('avg_mttr_seconds', sa.Float(), nullable=True),
    sa.Column('p50_seconds', sa.Float(), nullable=True),
    sa.Column('p95_seconds', sa.Float(), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_mv_mttr_by_class_failure_class'), 'mv_mttr_by_class', ['failure_class'], unique=True)
    op.create_table('mv_overview_snapshot',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('total_failures', sa.Integer(), nullable=False),
    sa.Column('top_failure_class', sa.String(length=255), nullable=True),
    sa.Column('failure_classes', postgresql.JSON(astext_type=Text()), nullable=True),
    sa.Column('systemic_count', sa.Integer(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('mv_pipeline_stages',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('stage_id', sa.String(length=255), nullable=False),
    sa.Column('pass_count', sa.Integer(), nullable=False),
    sa.Column('fail_count', sa.Integer(), nullable=False),
    sa.Column('warn_count', sa.Integer(), nullable=False),
    sa.Column('total', sa.Integer(), nullable=False),
    sa.Column('health_rate', sa.Float(), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_mv_pipeline_stages_stage_id'), 'mv_pipeline_stages', ['stage_id'], unique=True)
    op.create_table('pending_actions',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('action_type', sa.String(length=100), nullable=False),
    sa.Column('target', sa.String(length=255), nullable=False),
    sa.Column('parameters', postgresql.JSON(astext_type=Text()), nullable=True),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('proposed_by', sa.String(length=100), nullable=True),
    sa.Column('source_event_id', sa.String(length=255), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('proposed_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('reviewed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('reviewed_by', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_pending_actions_action_type'), 'pending_actions', ['action_type'], unique=False)
    op.create_table('pool_snapshots',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('pool_name', sa.String(length=255), nullable=False),
    sa.Column('available', sa.Integer(), nullable=False),
    sa.Column('ready', sa.Integer(), nullable=False),
    sa.Column('min_required', sa.Integer(), nullable=False),
    sa.Column('total_handles', sa.Integer(), nullable=False),
    sa.Column('captured_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_pool_snap_name_time', 'pool_snapshots', ['pool_name', 'captured_at'], unique=False)
    op.create_index(op.f('ix_pool_snapshots_captured_at'), 'pool_snapshots', ['captured_at'], unique=False)
    op.create_index(op.f('ix_pool_snapshots_pool_name'), 'pool_snapshots', ['pool_name'], unique=False)
    op.create_table('proposed_classifications',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('run_id', sa.String(length=255), nullable=False),
    sa.Column('stage_id', sa.String(length=255), nullable=False),
    sa.Column('original_message', sa.Text(), nullable=True),
    sa.Column('proposed_class', sa.String(length=255), nullable=False),
    sa.Column('proposed_conditions', postgresql.JSON(astext_type=Text()), nullable=True),
    sa.Column('confidence', sa.Float(), nullable=True),
    sa.Column('llm_model', sa.String(length=255), nullable=True),
    sa.Column('proposed_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('reviewed', sa.Boolean(), nullable=False),
    sa.Column('approved', sa.Boolean(), nullable=True),
    sa.Column('reviewed_by', sa.String(length=255), nullable=True),
    sa.Column('reviewed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('llm_metric_id', sa.Integer(), nullable=True),
    sa.Column('quality_outcome', sa.String(length=10), nullable=True),
    sa.Column('quality_passed', sa.Boolean(), nullable=True),
    sa.Column('quality_details', postgresql.JSON(astext_type=Text()), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('provisioning_snapshots',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('captured_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('total', sa.Integer(), nullable=False),
    sa.Column('started', sa.Integer(), nullable=False),
    sa.Column('failed', sa.Integer(), nullable=False),
    sa.Column('failure_rate', sa.Float(), nullable=True),
    sa.Column('by_state', postgresql.JSON(astext_type=Text()), nullable=True),
    sa.Column('summit_total', sa.Integer(), nullable=True),
    sa.Column('summit_started', sa.Integer(), nullable=True),
    sa.Column('summit_failed', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_provisioning_snapshots_captured_at'), 'provisioning_snapshots', ['captured_at'], unique=False)
    op.create_table('receipts',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('receipt_type', sa.String(length=100), nullable=False),
    sa.Column('phase', sa.String(length=10), nullable=True),
    sa.Column('data', postgresql.JSON(astext_type=Text()), nullable=False),
    sa.Column('passed', sa.Boolean(), nullable=False),
    sa.Column('generated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_receipts_phase'), 'receipts', ['phase'], unique=False)
    op.create_index(op.f('ix_receipts_receipt_type'), 'receipts', ['receipt_type'], unique=False)
    op.create_table('remediations',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('run_id', sa.String(length=255), nullable=False),
    sa.Column('stage_id', sa.String(length=255), nullable=False),
    sa.Column('failure_class', sa.String(length=255), nullable=False),
    sa.Column('remediation_id', sa.String(length=255), nullable=False),
    sa.Column('action_taken', sa.Text(), nullable=True),
    sa.Column('resolved', sa.Boolean(), nullable=True),
    sa.Column('resolved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('verification_eval_id', sa.Integer(), nullable=True),
    sa.Column('applied_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('applied_by', sa.String(length=255), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_remediations_failure_class'), 'remediations', ['failure_class'], unique=False)
    op.create_index(op.f('ix_remediations_remediation_id'), 'remediations', ['remediation_id'], unique=False)
    op.create_index(op.f('ix_remediations_run_id'), 'remediations', ['run_id'], unique=False)
    op.create_table('resolution_records',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('lab_code', sa.String(length=255), nullable=False),
    sa.Column('cluster', sa.String(length=100), nullable=True),
    sa.Column('failure_class', sa.String(length=255), nullable=False),
    sa.Column('failing_eval_id', sa.Integer(), nullable=True),
    sa.Column('resolved_eval_id', sa.Integer(), nullable=True),
    sa.Column('remediation_id', sa.Integer(), nullable=True),
    sa.Column('resolution_type', sa.String(length=50), nullable=False),
    sa.Column('resolved_by', sa.String(length=255), nullable=True),
    sa.Column('resolution_action', sa.Text(), nullable=True),
    sa.Column('detected_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('resolved_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('ttr_seconds', sa.Float(), nullable=True),
    sa.Column('audit_evidence', postgresql.JSON(astext_type=Text()), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_resolution_records_cluster'), 'resolution_records', ['cluster'], unique=False)
    op.create_index(op.f('ix_resolution_records_failure_class'), 'resolution_records', ['failure_class'], unique=False)
    op.create_index(op.f('ix_resolution_records_lab_code'), 'resolution_records', ['lab_code'], unique=False)
    op.create_index(op.f('ix_resolution_records_resolution_type'), 'resolution_records', ['resolution_type'], unique=False)
    op.create_table('runs',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('run_id', sa.String(length=255), nullable=False),
    sa.Column('demo_id', sa.String(length=255), nullable=False),
    sa.Column('namespace', sa.String(length=255), nullable=False),
    sa.Column('requested_by', sa.String(length=255), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('rubric_version', sa.String(length=50), nullable=False),
    sa.Column('git_sha', sa.String(length=64), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('lab_code', sa.String(length=255), nullable=True),
    sa.Column('cluster_name', sa.String(length=255), nullable=True),
    sa.Column('trigger_source', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_runs_cluster_name'), 'runs', ['cluster_name'], unique=False)
    op.create_index(op.f('ix_runs_lab_code'), 'runs', ['lab_code'], unique=False)
    op.create_index(op.f('ix_runs_run_id'), 'runs', ['run_id'], unique=True)
    op.create_table('sandbox_api_metrics',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('captured_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('api_healthy', sa.Boolean(), nullable=True),
    sa.Column('replicas_desired', sa.Integer(), nullable=True),
    sa.Column('replicas_ready', sa.Integer(), nullable=True),
    sa.Column('queue_depth', sa.Integer(), nullable=True),
    sa.Column('total_sandboxes', sa.Integer(), nullable=True),
    sa.Column('active', sa.Integer(), nullable=True),
    sa.Column('failing', sa.Integer(), nullable=True),
    sa.Column('crashloop', sa.Integer(), nullable=True),
    sa.Column('by_cluster', postgresql.JSON(astext_type=Text()), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_sandbox_api_metrics_captured_at'), 'sandbox_api_metrics', ['captured_at'], unique=False)
    op.create_table('scan_snapshots',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('scan_type', sa.String(length=50), nullable=False),
    sa.Column('data', postgresql.JSON(astext_type=Text()), nullable=False),
    sa.Column('scanned_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_scan_snapshots_scan_type'), 'scan_snapshots', ['scan_type'], unique=False)
    op.create_index(op.f('ix_scan_snapshots_scanned_at'), 'scan_snapshots', ['scanned_at'], unique=False)
    op.create_table('stages',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('run_id', sa.String(length=255), nullable=False),
    sa.Column('stage_id', sa.String(length=255), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('duration_seconds', sa.Float(), nullable=True),
    sa.Column('result_outcome', sa.String(length=50), nullable=True),
    sa.Column('result_failure_class', sa.String(length=255), nullable=True),
    sa.Column('result_message', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_stages_result_failure_class'), 'stages', ['result_failure_class'], unique=False)
    op.create_index(op.f('ix_stages_run_id'), 'stages', ['run_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_stages_run_id'), table_name='stages')
    op.drop_index(op.f('ix_stages_result_failure_class'), table_name='stages')
    op.drop_table('stages')
    op.drop_index(op.f('ix_scan_snapshots_scanned_at'), table_name='scan_snapshots')
    op.drop_index(op.f('ix_scan_snapshots_scan_type'), table_name='scan_snapshots')
    op.drop_table('scan_snapshots')
    op.drop_index(op.f('ix_sandbox_api_metrics_captured_at'), table_name='sandbox_api_metrics')
    op.drop_table('sandbox_api_metrics')
    op.drop_index(op.f('ix_runs_run_id'), table_name='runs')
    op.drop_index(op.f('ix_runs_lab_code'), table_name='runs')
    op.drop_index(op.f('ix_runs_cluster_name'), table_name='runs')
    op.drop_table('runs')
    op.drop_index(op.f('ix_resolution_records_resolution_type'), table_name='resolution_records')
    op.drop_index(op.f('ix_resolution_records_lab_code'), table_name='resolution_records')
    op.drop_index(op.f('ix_resolution_records_failure_class'), table_name='resolution_records')
    op.drop_index(op.f('ix_resolution_records_cluster'), table_name='resolution_records')
    op.drop_table('resolution_records')
    op.drop_index(op.f('ix_remediations_run_id'), table_name='remediations')
    op.drop_index(op.f('ix_remediations_remediation_id'), table_name='remediations')
    op.drop_index(op.f('ix_remediations_failure_class'), table_name='remediations')
    op.drop_table('remediations')
    op.drop_index(op.f('ix_receipts_receipt_type'), table_name='receipts')
    op.drop_index(op.f('ix_receipts_phase'), table_name='receipts')
    op.drop_table('receipts')
    op.drop_index(op.f('ix_provisioning_snapshots_captured_at'), table_name='provisioning_snapshots')
    op.drop_table('provisioning_snapshots')
    op.drop_table('proposed_classifications')
    op.drop_index(op.f('ix_pool_snapshots_pool_name'), table_name='pool_snapshots')
    op.drop_index(op.f('ix_pool_snapshots_captured_at'), table_name='pool_snapshots')
    op.drop_index('idx_pool_snap_name_time', table_name='pool_snapshots')
    op.drop_table('pool_snapshots')
    op.drop_index(op.f('ix_pending_actions_action_type'), table_name='pending_actions')
    op.drop_table('pending_actions')
    op.drop_index(op.f('ix_mv_pipeline_stages_stage_id'), table_name='mv_pipeline_stages')
    op.drop_table('mv_pipeline_stages')
    op.drop_table('mv_overview_snapshot')
    op.drop_index(op.f('ix_mv_mttr_by_class_failure_class'), table_name='mv_mttr_by_class')
    op.drop_table('mv_mttr_by_class')
    op.drop_index(op.f('ix_mv_lab_eval_summary_lab_code'), table_name='mv_lab_eval_summary')
    op.drop_index(op.f('ix_mv_lab_eval_summary_cluster_name'), table_name='mv_lab_eval_summary')
    op.drop_table('mv_lab_eval_summary')
    op.drop_index(op.f('ix_mv_evaluation_trends_cluster_name'), table_name='mv_evaluation_trends')
    op.drop_index(op.f('ix_mv_evaluation_trends_bucket'), table_name='mv_evaluation_trends')
    op.drop_table('mv_evaluation_trends')
    op.drop_index(op.f('ix_mv_cluster_summary_cluster_name'), table_name='mv_cluster_summary')
    op.drop_table('mv_cluster_summary')
    op.drop_index(op.f('ix_llm_metrics_prompt_hash'), table_name='llm_metrics')
    op.drop_index(op.f('ix_llm_metrics_lab_code'), table_name='llm_metrics')
    op.drop_index(op.f('ix_llm_metrics_endpoint'), table_name='llm_metrics')
    op.drop_index(op.f('ix_llm_metrics_called_at'), table_name='llm_metrics')
    op.drop_table('llm_metrics')
    op.drop_index(op.f('ix_llm_feedback_llm_metric_id'), table_name='llm_feedback')
    op.drop_table('llm_feedback')
    op.drop_table('lab_remediation_config')
    op.drop_index(op.f('ix_lab_mappings_ci_base'), table_name='lab_mappings')
    op.drop_table('lab_mappings')
    op.drop_index(op.f('ix_investigations_lab_code'), table_name='investigations')
    op.drop_index(op.f('ix_investigations_job_id'), table_name='investigations')
    op.drop_index(op.f('ix_investigations_failure_class'), table_name='investigations')
    op.drop_index(op.f('ix_investigations_cluster'), table_name='investigations')
    op.drop_index('idx_inv_status', table_name='investigations')
    op.drop_index('idx_inv_lab_fc', table_name='investigations')
    op.drop_table('investigations')
    op.drop_index(op.f('ix_evidence_stage_id'), table_name='evidence')
    op.drop_index(op.f('ix_evidence_run_id'), table_name='evidence')
    op.drop_index(op.f('ix_evidence_evidence_id'), table_name='evidence')
    op.drop_table('evidence')
    op.drop_index(op.f('ix_event_log_stage_id'), table_name='event_log')
    op.drop_index(op.f('ix_event_log_lab_code'), table_name='event_log')
    op.drop_index(op.f('ix_event_log_failure_class'), table_name='event_log')
    op.drop_index(op.f('ix_event_log_event_type'), table_name='event_log')
    op.drop_index(op.f('ix_event_log_event_id'), table_name='event_log')
    op.drop_index(op.f('ix_event_log_cluster_name'), table_name='event_log')
    op.drop_table('event_log')
    op.drop_index(op.f('ix_evaluations_sub_class'), table_name='evaluations')
    op.drop_index(op.f('ix_evaluations_stage_id'), table_name='evaluations')
    op.drop_index(op.f('ix_evaluations_run_id'), table_name='evaluations')
    op.drop_index(op.f('ix_evaluations_lab_code'), table_name='evaluations')
    op.drop_index(op.f('ix_evaluations_failure_class'), table_name='evaluations')
    op.drop_index(op.f('ix_evaluations_cluster_name'), table_name='evaluations')
    op.drop_index('idx_eval_lab_stage', table_name='evaluations')
    op.drop_index('idx_eval_lab_cluster', table_name='evaluations')
    op.drop_index('idx_eval_cluster_outcome', table_name='evaluations')
    op.drop_table('evaluations')
    op.drop_index(op.f('ix_constraint_violations_violation_type'), table_name='constraint_violations')
    op.drop_index(op.f('ix_constraint_violations_lab_code'), table_name='constraint_violations')
    op.drop_table('constraint_violations')
    op.drop_index(op.f('ix_audit_log_action_type'), table_name='audit_log')
    op.drop_table('audit_log')
    op.drop_index(op.f('ix_aap_job_metrics_captured_at'), table_name='aap_job_metrics')
    op.drop_table('aap_job_metrics')
    # ### end Alembic commands ###
