apiVersion: v1
kind: ServiceAccount
metadata:
  name: stargate-api
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: stargate-api-role
rules:
  - apiGroups: [""]
    resources: ["pods", "services", "configmaps"]
    verbs: ["get", "list"]
  - apiGroups: [""]
    resources: ["secrets"]
    verbs: ["get"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: stargate-api-binding
subjects:
  - kind: ServiceAccount
    name: stargate-api
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: stargate-api-role
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: stargate-scanner
---
{{- if .Values.oauth.enabled }}
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: stargate-oauth
  annotations:
    serviceaccounts.openshift.io/oauth-redirectreference.primary: |
      {"kind":"OAuthRedirectReference","apiVersion":"v1","reference":{"kind":"Route","name":"stargate"}}
{{- end }}
