apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: stargate
spec:
  host: {{ required "routes.frontend must be set" .Values.routes.frontend }}
  to:
    kind: Service
    name: stargate-frontend
  port:
    targetPort: {{ .Values.oauth.enabled | ternary 4180 (.Values.frontend.port | int) }}
  tls:
    termination: edge
    insecureEdgeTerminationPolicy: Redirect
---
apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: stargate-api
spec:
  host: {{ required "routes.api must be set" .Values.routes.api }}
  to:
    kind: Service
    name: stargate-api
  port:
    targetPort: {{ .Values.oauth.enabled | ternary 4180 (.Values.api.port | int) }}
  tls:
    termination: edge
    insecureEdgeTerminationPolicy: Redirect
