apiVersion: v1
kind: Secret
metadata:
  name: stargate-secrets
type: Opaque
stringData:
  postgres-password: {{ .Values.postgres.password | quote }}
  litellm-api-key: {{ .Values.secrets.litellmApiKey | quote }}
  admin-api-key: {{ .Values.secrets.adminApiKey | quote }}
