"""PR text generator — produces reviewable PR descriptions from AI proposals.

Generates PR-ready markdown text from failure summaries, rubric diffs,
and runbook updates. All output is marked as proposed/unapproved.
"""

from __future__ import annotations

from typing import List, Optional

from api.app.ai.models import AIProposal, FailureSummary, RubricDiff, RunbookUpdate


def generate_pr_text(
    proposals: List[AIProposal],
    run_id: str,
    title_prefix: str = "sdf",
) -> dict:
    """Generate a PR title and body from a list of AI proposals.

    Returns a dict with: title, body, labels, status, approved, requires_human_review.
    """
    rubric_diffs = [p for p in proposals if isinstance(p, RubricDiff)]
    runbook_updates = [p for p in proposals if isinstance(p, RunbookUpdate)]
    summaries = [p for p in proposals if isinstance(p, FailureSummary)]

    change_types = set()
    for p in proposals:
        if isinstance(p, RubricDiff):
            change_types.add("rubric")
        elif isinstance(p, RunbookUpdate):
            change_types.add("runbook")
        elif isinstance(p, FailureSummary):
            change_types.add("analysis")

    type_str = "+".join(sorted(change_types)) if change_types else "proposal"
    title = f"[{title_prefix}] Proposed {type_str} changes from run {run_id}"

    body_parts = [
        "## Summary",
        "",
        f"Automated proposals generated from run `{run_id}`.",
        "",
        "> **Status: proposed** — requires human review before merge.",
        "",
    ]

    if summaries:
        body_parts.append("## Failure Analysis")
        body_parts.append("")
        for s in summaries:
            body_parts.append(f"### Run: {s.source_run_id}")
            if s.failed_stages:
                body_parts.append(f"**Failed stages:** {', '.join(s.failed_stages)}")
            body_parts.append(f"**Root cause:** {s.root_cause_hypothesis}")
            body_parts.append("")
            if s.recommended_actions:
                body_parts.append("**Recommended actions:**")
                for action in s.recommended_actions:
                    body_parts.append(f"- {action}")
                body_parts.append("")

    if rubric_diffs:
        body_parts.append("## Rubric Changes")
        body_parts.append("")
        for diff in rubric_diffs:
            body_parts.append(f"### {diff.rubric_id} ({diff.change_type})")
            body_parts.append(f"{diff.description}")
            body_parts.append("")
            body_parts.append(f"**Rationale:** {diff.rationale}")
            body_parts.append("")
            body_parts.append("```yaml")
            body_parts.append(diff.proposed_yaml.rstrip())
            body_parts.append("```")
            body_parts.append("")

    if runbook_updates:
        body_parts.append("## Runbook Updates")
        body_parts.append("")
        for update in runbook_updates:
            body_parts.append(f"### {update.target_id} ({update.change_type})")
            body_parts.append(f"{update.description}")
            body_parts.append("")
            body_parts.append(f"**Rationale:** {update.rationale}")
            body_parts.append("")
            body_parts.append("```yaml")
            body_parts.append(update.proposed_content.rstrip())
            body_parts.append("```")
            body_parts.append("")

    body_parts.extend([
        "---",
        "",
        "**This PR was generated by Summit Demo Factory AI recommendations.**",
        "All proposals require human review. No changes have been applied automatically.",
    ])

    return {
        "title": title,
        "body": "\n".join(body_parts),
        "labels": ["sdf-proposal", "ai-generated", "requires-review"],
        "status": "proposed",
        "approved": False,
        "requires_human_review": True,
        "source_run_id": run_id,
        "proposal_count": len(proposals),
    }
